version: "3.8"

services:

  &db postgres:
    image: postgres:15.2
    env_file:
      - .env
    ports:
      - "5432:5432"

  db-migration:
    image: hellconnector/tradematebot:3.11-slim-buster
    environment:
      POSTGRES_HOST: *db
    env_file:
      - .env
    working_dir: "/app/bot/db"
    entrypoint: ["alembic", "upgrade", "head"]
    depends_on:
      - postgres

  bot:
    image: hellconnector/tradematebot:3.11-slim-buster
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: *db
    env_file:
      - .env
    depends_on:
      - postgres
      - db-migration

  mini-app:
    image: hellconnector/tradematebot:3.11-slim-buster
    environment:
      POSTGRES_HOST: *db
    env_file:
      - .env
    working_dir: "/app"
    entrypoint: ["uvicorn", "mini-app.main:app", "--host", "0.0.0.0", "--port", "80"]
    ports:
      - "80:80"
    depends_on:
      - postgres
      - db-migration
      - bot
