[tool.poetry]
name = "tradematebot"
version = "0.1.0"
description = "Telegram Bot that helps to monitor and track CS:GO investments"
authors = ["HellConnector <kavai.barbarian@gmail.com>"]
license = "Apache License 2.0"
readme = "README.md"

packages = [
    { include = "bot" }
]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.2"
SQLAlchemy = "^2.0.9"
python-telegram-bot = "^20.2"
asyncpg = "^0.27.0"
apscheduler = "^3.10.1"
pillow = "^9.5.0"
alembic = "^1.10.3"
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.262"
black = "^23.3.0"
memray = "^1.7.0"


[tool.poetry.group.parser.dependencies]
vdf = "^3.4"
aiohttp = "^3.8.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
venvPath = "."
venv = ".venv"
python.analysis.useLibraryCodeForTypes = true
# TODO remove when all issuies will be fixed
reportOptionalMemberAccess = false
reportOptionalSubscript = false
reportGeneralTypeIssues = false

[tool.ruff]
target-version = "py311"
