name: Update prices

on:
  workflow_dispatch:
  
  schedule:
    - cron: "5/30 * * * *"

jobs:
  update-prices:
    strategy:
      fail-fast: false
      matrix:
        segment: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry config virtualenvs.in-project true
          poetry install

      - name: Run worker script
        env:
          PYTHONUNBUFFERED: "1"
          PROXIES_URL: ${{ secrets.PROXIES_URL }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SEGMENT: ${{ matrix.segment }}
          ITEMS_IN_SEGMENT: "100"
        run: |
          cd price-worker
          poetry run price-worker
