name: Update prices

on:
  workflow_dispatch:

#  push:
#    branches:
#      - add-price-worker

jobs:
  update-prices:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install dependencies
        run: |
          python -m pip install poetry
          poetry config virtualenvs.in-project true
          poetry install

      - name: run worker script
        env:
          PYTHONUNBUFFERED: "1"
          PROXIES_URL: ${{ secrets.PROXIES_URL }}
        run: |
          cd price-worker
          poetry run price-worker
